on:
  schedule:
    - cron: '00 8 01 * *'
  workflow_dispatch:

permissions:
  contents: write

name: Dump AAGuids

jobs:
  build:
    runs-on: ubuntu-latest
    name: Dump latest AAGUIDs
    steps:
      - uses: actions/checkout@v3
      - name: Dump AAGUIDs
        run: |
          $uri = 'https://raw.githubusercontent.com/nicolonsky/AAGuids/main/public/mdsblob.json'
          $targetPath = 'Watchlists/aaguids.json'
          $data = Invoke-RestMethod -Uri $uri
          $data | Where-Object {$_.protocolFamily -eq "fido2"} | ForEach-Object { 
            [PSCustomObject]@{
              AAGuid = $PSItem.aaguid
              Name = $PSItem.description
            }
          } | Sort-Object -Property Name | ConvertTo-Json | Set-Content $targetPath -Encoding utf8 -Force
        shell: pwsh
      - name: Commit and push changes
        run: |
          git config --global user.name 'AAGuid dump'
          git config --global user.email 'nicolonsky@users.noreply.github.com'
          git add .
          git commit -am "AAGuid dump"
          git push
